### ISSUE TITLE
multiprocessing/pool.py, TypeError: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by afpapqy** [bolianchen/pytorch_depth_from_videos_in_the_wild#14] opened 2022-08-11 12:48 UTC
I wanted to use gen_data.py to convert my video to the desired format. I set dataset_name, DATASET_dir, save_dir, img_height, and img_width, and use the default values for the rest. However, after successfully processing 500 frames, the error message is as follows: [Python Multiprocessing Logging Error - TypeError: an integer is required (got type NoneType)].  What should I do?

**Comment by bolianchen** [comment] 2022-08-11 14:08
Hi @afpapqy 
Please copy and paste all the error messages for me to check. I guess adding --single_process to your command should be a quick workaround but compromise on the runtime.

**Comment by afpapqy** [comment] 2022-08-12 02:04
> Hi @afpapqy Please copy and paste all the error messages for me to check. I guess adding --single_process to your command should be a quick workaround but compromise on the runtime.

/home/fupan/anaconda3/envs/py38/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
0 raw frames have been processed
500 raw frames have been processed
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "gen_data.py", line 195, in _gen_example_star
    return _gen_example(*params)
  File "gen_data.py", line 191, in _gen_example
    all_examples[key] = example
  File "<string>", line 2, in __setitem__
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
TypeError: an integer is required (got type NoneType)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gen_data.py", line 223, in <module>
    _generate_data()
  File "gen_data.py", line 122, in _generate_data
    pool.map(
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: an integer is required (got type NoneType)
——————————————————
Note that the above error was generated in Pytorch1.8.2 + python3.8, and I was able to run it successfully under another combination with Pytorch1.7.1 + python3.6.

**Comment by JiaoRunyu** [comment] 2022-09-04 02:27
> 请复制并粘贴所有错误消息供我检查。我想将 --single_process 添加到您的命令应该是一种快速的解决方法

> > 你好@afpapqy请复制并粘贴所有错误的快速解决方法消息供我检查。我想将 --single_process 添加到您的命令应该是，但会影响运行时。
> 
> /home/fupan/anaconda3/envs/py38/lib/python3.8/site-packages/scipy/init .py:146：**UserWarning**：此版本需要 NumPy 版本 >=1.16.5 和 <1.23.0 SciPy（到检测到版本 1.23.1 warnings.warn(f"A NumPy 版本 >={np_minversion} 和 <{np_maxversion}" 0 个原始帧已处理 500 个原始帧 multiprocessing.pool.RemoteTraceback: """ Traceback (最近一次调用最后一次）： 文件“/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py”，第125行，在worker result = (True, func(*args, **kwds) ) 文件“/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py”，第48行，在mapstar 返回列表(map(*args)) 文件“gen_data.py”，第195行，在_gen_example_star 返回_gen_example(*params) 文件“gen_data.py”，第 191 行，在 _gen_example all_examples[key] = 示例 文件“”，第2行，在**setitem** 文件“/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/managers.py”，第834行，在_callmethod conn. send((self._id, methodname, args, kwds)) 文件“/home/fupan/anaconda3 /envs/py38/lib/python3.8/multiprocessing/connection.py”，第206行，在 self._send_bytes( _ForkingPickler.dumps(obj)) 文件“/home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py”，第411行，在_send_bytes self._send(header + buf) 文件“/ home/fupan/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py”，第 368 行，在 _send n = write(self._handle, buf) TypeError: an integer is required (got type无类型) """
> 
> 上述异常是以下异常的直接原因：
> 
> 回溯（最后一次调用）： 文件“gen_data.py”，第223行，在 _generate_data() 文件“gen_data.py”，122行，在_generate_data pool.map( 文件"/home/fupan/anaconda3/envs/ py38 /lib/python3.8/multiprocessing/pool.py”，第 364 行，在 map 中 返回 self._map_async(func, iterable, mapstar, chunksize).get() 文件“/home/fupan/anaconda3/envs/ py38/lib /python3.8/multiprocessing/pool.py", line 771, in get raise self._value TypeError: an integer is required (got type NoneType) ——————————————— ——— 注意上面的错误是在Pytorch1.8.2 + python3.8中产生的，我在Pytorch1.7.1 + python3.6的另一种组合下能够成功运行。

Hello,did you solve this?I have the same question with you.

**Comment by JiaoRunyu** [comment] 2022-09-04 02:48
> Hi @afpapqy Please copy and paste all the error messages for me to check. I guess adding --single_process to your command should be a quick workaround but compromise on the runtime.

It works!Thx

**Comment by bolianchen** [comment] 2022-09-08 07:04
@afpapqy @JiaoRunyu 
Thank you, guys. I would like to summarize this issue and close it.

The issue is due to the compatibility of the codes with Pytorch newer than 1.8. Please consider using the recommended  Pytorch version mentioned in the environment-setup section.
https://github.com/bolianchen/pytorch_depth_from_videos_in_the_wild#environment-setup

**Closed by bolianchen** 2022-09-08 07:04 UTC
